Contact page
hicsail/hicsail.github.io pull request #55
Opened 2023-10-11 18:46 UTC by ukamila

funnily enough contact page is not changed in this PR, but rather new projects were added and small css changes

2023-10-11 18:55 UTC, gregfrasco commented
Cannot find module 'react-awesome-reveal'

2023-10-11 18:56 UTC, gregfrasco requested changes
minor changes, but couldn't load the page to comment on that.

2023-10-11 18:56 UTC, gregfrasco commented on .vscode/settings.json
ignore .vscode folder

2023-10-11 18:56 UTC, gregfrasco commented on .gitignore
remove white space changes

2023-10-13 20:13 UTC, gregfrasco approved these changes
Minor changes

2023-10-13 20:13 UTC, gregfrasco commented on .vscode/settings.json
Also we need to remove this file from being tracked

2023-10-13 20:21 UTC, gregfrasco approved these changes

2023-10-13 21:13 UTC, ukamila commented
everything's working now, but pending changes

2023-10-13 21:14 UTC, merged